### ISSUE TITLE
Package install

### ISSUE THREAD

**Issue by asghaier76** [0xcert/framework#267]
Why can't install the whole 0xcert package instead of each module alone

**Comment by MoMannn** [comment]
Since 0xcert framework can be used on the frontend and the backend we decided to split packages for size/load speed optimisation reason. So if you are using it on the frontend you only use the parts you need and with that you minimize the size of the javascript files that need to be loaded.

**Comment by xpepermint** [comment]
This is to minimize the code size which is especially important for front-end development. You include in your project only what you need. Maybe you need just the certification module or just the asset ledger part. Note also that we will add more packages with more providers, for more blockchains with more features and a single package would not be sustainable.

**Comment by xpepermint** [comment]
@MoMannn you beat me :).
