### ISSUE TITLE
Sign a transaction (Mutation) 

### ISSUE THREAD

**Issue by asghaier76** [0xcert/framework#268]
I am using the HttpProvider and upon sending a transaction (Mutation) I see no capability of importing my private key and sign the transaction before sending it.

    import { HttpProvider } from '@0xcert/ethereum-http-provider';
    import { AssetLedger, AssetLedgerCapability } from '@0xcert/ethereum-asset-ledger';

    const provider = new HttpProvider({
      accountId: '0xcc567f78e8821fb8d19f7e6240f44553ce3dbfce',
      url: 'https://ropsten.infura.io/v3/06312ac7a50b4bd49762abc5cf79dab8',
    });
    const ledgerId = '0xcc567f78e8821fb8d19f7e6240f44553ce3dbfce';
    
    // create ledger instance
    const ledger = new AssetLedger(provider, ledgerId);
    ledger.getInfo()
    .then(res => {
      console.log(res);
    }, (err) => {
      console.log(err)
    });

    const capabilities = [
      AssetLedgerCapability.TOGGLE_TRANSFERS,
    ];
    const recipe = {
        name: 'Utility token',
        symbol: 'UCC',
        uriBase: 'http://domain.com/assets/',
        schemaId: '0x0000000000000000000000000000000000000000000000000000000000000000',
        capabilities,
    };
    
    // perform mutation
    AssetLedger.deploy(provider, recipe)
    .then(res => {
      console.log(res);
    }, (err) => {
      console.log(err)
    });

The ledger.getInfo() returns a response with the expected output while the deploy method returns an error 
ProviderError: GenericProvider error [issue: 0]
{"jsonrpc":"2.0","id":9,"error":{"code":-32601,"message":"The method eth_sendTransaction does not exist/is not available"}}

**Comment by xpepermint** [comment]
Already in the pipeline.

**Comment by asghaier76** [comment]
Any update on when this feature will be added to the framework

**Comment by xpepermint** [comment]
No date available at the moment, but this is defenetly a priority. Not sure what to do with MetaMask.

**Comment by asghaier76** [comment]
For mobile applications MetaMask provider is not an option.

**Comment by xpepermint** [comment]
True, but when we add support for this feature, it must work with all major wallets.

**Comment by xpepermint** [comment]
Closing in favor of https://github.com/0xcert/framework/pull/548.
