### ISSUE TITLE
Error in node-fetch when building 

### ISSUE THREAD

**Issue by asghaier76** [0xcert/framework#277]
As I try to build my app I get this error message

Error: ./node_modules/@0xcert/utils/dist/methods/fetch.js Module not found: Error: Can't resolve
            'node-fetch' in '../nft/node_modules/@0xcert/utils/dist/methods' resolve
            'node-fetch' in '../nft/node_modules/@0xcert/utils/dist/methods' Parsed request

**Comment by MoMannn** [comment]
Do `npm install node-fetch` that should solve it. I'm guessing since you are not using node it didn't get the dependency by default.

**Comment by asghaier76** [comment]
Thanks, resolved.

**Comment by xpepermint** [comment]
@asghaier76 looking into this right now.

**Comment by xpepermint** [comment]
Got it. We have `node-fetch` under `devDependencies` instead of `dependencies`. Pushing a fix in a minute.

**Comment by xpepermint** [comment]
Fixed in https://github.com/0xcert/framework/pull/278.

**Comment by asghaier76** [comment]
you rock guys.
