### ISSUE TITLE
Fix broken short link

### ISSUE THREAD

**Issue by fulldecent** [0xcert/framework#297]
Related #161

https://github.com/0xcert/framework/blob/master/packages/0xcert-ethereum-utils-contracts/src/contracts/permission/claimable.sol#L8

**Comment by fulldecent** [comment]
Also affected https://github.com/0xcert/framework/blob/master/packages/0xcert-ethereum-utils-contracts/src/contracts/utils/erc165.sol

**Comment by MoMannn** [comment]
#301
