### ISSUE TITLE
Question about certification

### ISSUE THREAD

**Issue by pizza-r0b** [0xcert/framework#302]
Hi there. Not sure this is the correct place for this, but I wanted to ask you guys a question. I am interested in using the 0xcert frameworks certification capabilities, but there's something I am not understanding. Say I have the following data:

```
{
    description: 'A weapon for the Troopers game which can severely injure the enemy.',
    image: 'https://troopersgame.com/dog.jpg',
    name: 'Magic Sword'
}
```

Description and image are added to the public evidence file. I own the token and know what the private name property is. Why would I create a proof for name using `disclose` if description and image are already public. Couldn't I just say "Hey, third party the name is Magic Sword. Run it through the `imprint` method and you will get the imprint from the token". Either way the entire data object is required for the `calculate` function - so what's the point of the proofs? I must be missing something.

**Comment by xpepermint** [comment]
Hey @pizza-r0b and thanks for your interest in 0xcert. You are correct! The example above is a super simple example but it's not a good use case to understand it's value. Let's look at another fictitious example where all fields are private:
```
{
  firstName: 'John',
  lastName: 'Smith',
  age: 21,
}
```
Let's say you need to prove to someone that you are above 18 years old. You create an evidence file where you expose only `age` and you leave the rest of the fields private. These private data is known to you only. The evidence file is some sort of "compiled" certificate containing [merkle-tree](https://en.wikipedia.org/wiki/Merkle_tree) hashes required to calculate the `imprint`. If the calculated imprint matches the one inside the token, a third party knows that the data you provided is correct. You should ignore the content of the evidence file (it's complex) and only use the API.

So, this way, you will expose only the information required by the third-party and keep the rest of the data private.

**Comment by pizza-r0b** [comment]
Great! Thanks for the information. What about transferring the token. Then two parties will have access to the private meta data. The non-owner could then act as if they own the token since they know what the private data is. How do we get around this? Also do an address check?

**Comment by xpepermint** [comment]
Good point. Well, it's obvious who the real owner is just by checking the asset's owner so he can not act as an owner. The previous owner can only act as a third-party to whom the current owner disclosed all the data. This is the same as in real life. You own a car, you know exactly what car that is and all the properties, you sell it to a friend, your friend now knows exactly which car he owns. He upgrades the car, now you have outdated information. It's the same concept here with NFTs.
