### ISSUE TITLE
Are base interface types too specific?

### ISSUE THREAD

**Issue by fulldecent** [0xcert/framework#310]
Opening up a quick discussion here on a small point.

https://github.com/0xcert/framework/blob/master/packages/0xcert-scaffold/src/core/value-ledger.ts#L8

```ts
/**
 * Value ledger methods.
 */
export interface ValueLedgerBase {
  readonly id: string;
  ...
```

The `id` is the account identifier. In Ethereum it might be appropriate to use a BigNumber here. Or better, a BigNumberUInt160. In MySQL this might be an int. And in MSSQL, this might be a UUID.

It might be best to use an opaque `any` here.

In the same way, we should double check the specificity of property types for other cross-platform interfaces.

**Comment by xpepermint** [comment]
That's why we use `string` which is common for cases like this in Javascript world. The `any` type would cause many problems in actual app development.
