### ISSUE TITLE
Better document toInteger

### ISSUE THREAD

**Issue by fulldecent** [0xcert/framework#315]
In to-integer.ts, the function toInteger is specified:

```ts
/**
 * Converts float number to integer.
 */
export function toInteger(val: number);
```

This fails on the following input:

https://stackblitz.com/edit/typescript-ms14nw

```ts
function toInteger(val: number) {
  return parseInt(`${val}`) || 0;
}

//let n: number = 2**54;
//let n:number = 9007199254740993;
let n: number = 2**100;

console.log(n);
console.log(toInteger(n));
console.log(Number.MAX_SAFE_INTEGER);
```

Not surprising, but still this behavior is undocumented.

Fun fact: you can use safely use one more than `Number.MAX_SAFE_INTEGER`. So for the test case you need to use TWO more than the highest safe integer!

**Comment by xpepermint** [comment]
So this is what you propose?
```ts
/**
 * Converts numeric values to integer.
 */
export function toInteger(val: number | string) {
  return parseInt(`${val}`) || 0;
}
```

**Comment by xpepermint** [comment]
https://github.com/0xcert/framework/pull/349
