### ISSUE TITLE
Document class properties

### ISSUE THREAD

**Issue by fulldecent** [0xcert/framework#318]
Many TypeScript class properties here are undocumented. I don't know if this type (JSDoc) of documentation is standardized for TypeScript:

```ts
export class ProviderError extends Error {
  /** The specific kind of error */
  public issue: ProviderIssue;
```

but it works in VS Code for IntelliSense. Also we can use this documentation to generate API docs. Also, somebody else might want to read this code some day! 

Recommend to add completed-docs to the tslint test suite. At a minimum, all methods and properties should be documented for all public+exported items.

**Comment by MoMannn** [comment]
#363
