### ISSUE TITLE
VUE-Example add screenshots

### ISSUE THREAD

**Issue by fulldecent** [0xcert/framework#319]
I ran the vue example. It works great!

<img width="885" alt="screen shot 2019-02-02 at 10 06 36 pm" src="https://user-images.githubusercontent.com/382183/52172154-c434f400-2737-11e9-8d62-8939d3722dfa.png">

Can we add some screenshots or other enticing visuals to get people to load it! Maybe we can put this screenshot in that README for now.

**Comment by xpepermint** [comment]
@fulldecent where would you put these images? The `vue` example should not be an important part of the repo.

**Comment by xpepermint** [comment]
Closing since this is more for testing metamask. We'll add a live example to the docs instead,

**Comment by fulldecent** [comment]
Cool, live example is way more fun!
