### ISSUE TITLE
Commit npm package lock files

### ISSUE THREAD

**Issue by fulldecent** [0xcert/framework#321]
Error message from Rush JS + NPM at:

https://travis-ci.org/0xcert/framework/jobs/488576308#L477

> npm notice created a lockfile as package-lock.json. You should commit this file.

---

Our builds are inconsistent -- this means the some code compiled on CI twice has different results:

* https://travis-ci.org/0xcert/framework/jobs/488576308
* https://travis-ci.org/0xcert/framework/builds/488027681

---

Normally, you would just commit the package-lock.json file and everything is good. But we should double check if using Rush requires us to follow a different pattern here.

**Comment by xpepermint** [comment]
Before you push commits just make sure you do `rush update --full && rush rebuild`, then you commit also the files that are regenerated by Rush

**Comment by fulldecent** [comment]
Ah, thanks for explaining! Today I learned that you need to recompile the code even if updating the static assets.

PR building here https://github.com/0xcert/framework/pull/316
