### ISSUE TITLE
Merkle implementation leaks emptiness of array

### ISSUE THREAD

**Issue by fulldecent** [0xcert/framework#323]
To prove this attack we need only look at the test case:

```
spec.test('exposes 0 from empty array', async (ctx) => {
  const values = [];
  const expose = [];
  const recipe = await ctx.get('merkle').notarize(values);
  const evidence = await ctx.get('merkle').disclose(recipe, expose);
  ctx.deepEqual(evidence, {
    values: [],
    nodes: [
      { index: 0, hash: 'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855' },
    ],
  });
});
```

And of course `e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855` is the hash of an empty input.

The function was called to expose no data. However, it has exposed the emptiness of the array.

**Comment by xpepermint** [comment]
Well ... it actually depends on the `hasher` which can use some other algorithm with a custom password. By default, this function is a simple `sha256` with no password. What is your suggestion?

**Comment by fulldecent** [comment]
Actually, this issue is a logical progression from #332 and #325. I'll go address those first.

**Comment by xpepermint** [comment]
@fulldecent Fixed here https://github.com/0xcert/framework/pull/381.
