### ISSUE TITLE
Merkle tests have opaque values

### ISSUE THREAD

**Issue by fulldecent** [0xcert/framework#324]
The tests fro the merkle package use opaque values:

```
spec.test('exposes 0 from empty array', async (ctx) => {
  const values = [];
  const expose = [];
  const recipe = await ctx.get('merkle').notarize(values);
  const evidence = await ctx.get('merkle').disclose(recipe, expose);
  ctx.deepEqual(evidence, {
    values: [],
    nodes: [
      { index: 0, hash: 'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855' },
    ],
  });
});
```

It can be difficult to reason about how some of these values were chosen.

Recommend to also explicitly generate these values in code and use two tests.

Example:

```
spec.test('exposes 0 from empty array', async (ctx) => {
  // Manually calculate the value
  const expectedHash = sha("");
  ctx.deepEqual(expectedHash, 'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855');

  // Use the library to calculate
  ...
  ctx.deepEqual(..., ... expectedHash)
});
```

**Comment by xpepermint** [comment]
These hash values are created from the README example.

**Comment by xpepermint** [comment]
As explained https://github.com/0xcert/framework/issues/331, for the sake of simplicity, all the hashes have been calculated by hand and placed in the tests. Replacing hashes with mechanics for calculating objects would be super complex and we would have to actually recreate the Cert class.

I agree we have to properly document this Cert algorithm. We'll add this to the docs or write a blog about this.
