### ISSUE TITLE
Merkle implementation vulnerable to brute force attack

### ISSUE THREAD

**Issue by fulldecent** [0xcert/framework#325]
This weakness should be solved or disclosed in documentation.

# Example from the tests

```ts
spec.test('exposes 5 from A, B, C, D', async (ctx) => {
  const values = ['A', 'B', 'C', 'D'];
  const expose = [0, 2];
  const recipe = await ctx.get('merkle').notarize(values);
  const evidence = await ctx.get('merkle').disclose(recipe, expose);
  ctx.deepEqual(evidence, {
    values: [
      { index: 0, value: 'A' },
      { index: 2, value: 'C' },
    ],
    nodes: [
      { index: 3, hash: 'df7e70e5021544f4834bbee64a9e3789febc4be81470df629cad6ddb03320a5c' },
      { index: 6, hash: 'dbf687a59392a9b4a1c1fe1527b776a85b971c583ea22a88e41cebf91215930c' },
    ],
  });
});
```

This is:

```
    n0
    |
---------
|       |
n1      n2
A       |
    ---------
    |       |
    n3      n4
    B       |
        ---------
        |       |
        n5      n6
        C       |
            ---------
            |       |
            n7      n8
            D       empty
```

Attacker has publicly learned:

- n6 = dbf687a59392a9b4a1c1fe1527b776a85b971c583ea22a88e41cebf91215930c
- n3 = df7e70e5021544f4834bbee64a9e3789febc4be81470df629cad6ddb03320a5c
- n1 = hash('A') = 559aead08264d5795d3909718cdd05abd49572e84fe55590eef31a88a08fdffd
- n5 = hash('C') = 6b23c0d5f35d1b11f9b683f0b0a617355deb11277d91ae091d399c655b87940d

By deduction they also know:

- n4 = 2deb44a999dcba4d19540f77611516cdd82cca3a91ce0981fdaf67988304afa3
  - This is hash("6b23c0d5f35d1b11f9b683f0b0a617355deb11277d91ae091d399c655b87940d" + "dbf687a59392a9b4a1c1fe1527b776a85b971c583ea22a88e41cebf91215930c")

By guessing various values for n3, they can recover the root hash and verify that the guess was correct.

# Recommendation

This limitation is OKAY. But we just need to clearly document it.

Alternatively, the design could be changed to remove this limitation. This will require adding non-deterministic ("random") data in.

**Comment by xpepermint** [comment]
True, brute force attack is always possible, but still, cracking the `sha256` is safe enough today, when this breaks, half of the world will break :). 

It's possible to use a password in the `@0xcert/merkle` and `@0xcert/cert` packages. You just pass a custom `hasher` to a package and you can use your own algorithm if you want.

How would you document this? Would you please open a PR for this?

**Comment by fulldecent** [comment]
I'm not talking about brute forcing the full key space of sha256 (that's hard).

Instead, this is talking about brute forcing the plain-text space of program inputs. If you pick a letter, ANY letter and hash it using the current merkle implementation then I can figure out which letter you picked. That's bad!

One solution is to add a random 256-bit nonce to every leaf node hash. This is discussed at https://fulldecent.blogspot.com/2018/11/storing-arbitrary-length-data-in-merkle.html please see the section "Bonus: note about brute force attack". This requires disclosing the value AND the random nonce for every proof.

**Comment by xpepermint** [comment]
I know what you mean and I agree. To keep things simple the default algorithm uses no passwords but you can pass a custom `hasher` function when initializing the `Cert` class.

How would you enable passwords by default? I had a `nonce` field in `values` but I removed it because it looked complex.

**Comment by xpepermint** [comment]
@fulldecent Based on NY meeting I've added support for certification nonces https://github.com/0xcert/framework/pull/381.
