### ISSUE TITLE
Inconsistent example variable naming

### ISSUE THREAD

**Issue by fulldecent** [0xcert/framework#329]
In the 0xcert-cert package the README uses:

    const imprints = await cert.notarize(data);

But in the merkle package the same code is:

    const recipe = await merkle.notarize(values);

Variable names should be consistent across packages for clarity.

**Comment by fulldecent** [comment]
Also 

    const evidence = await merkle.disclose(recipe, expose);

vs

    const imprints = await cert.disclose(exampleData, [ ...paths... ]);

**Comment by xpepermint** [comment]
https://github.com/0xcert/framework/pull/341
