### ISSUE TITLE
0xcert-cert does not need data to generate root hash

### ISSUE THREAD

**Issue by fulldecent** [0xcert/framework#330]
In the example:

    // Verify data object against imprints generated with function `disclose` (if object is valid, an imprint is the right root hash).
    const imprint = await cert.calculate(data, imprints);

both the data and the imprints are used.

However scrolling up, we see

    // Expose selected data keys (returns imprints and exposed values from which an imprint can be calculated).
    const imprints = await cert.disclose(exampleData, [ ...paths... ]);

therefore it would seem that the `data` parameter to `cert.calculate` is redundant.

**Comment by xpepermint** [comment]
Probably related to https://github.com/0xcert/framework/pull/328. The `data` is required because you are calculating (method `calculate`) an `imprint` from `recipes` (built by `disclose` method) for a specific data object `data`.
