### ISSUE TITLE
Cert tests uses opaque values

### ISSUE THREAD

**Issue by fulldecent** [0xcert/framework#331]
Related: #324

In the certs package, the test runs against opaque values:

    ctx.is(imprint, 'fe3ea95fa6bda2001c58fd13d5c7655f83b8c8bf225b9dfa7b8c7311b8b68933');

This can be difficult to confirm the test is running properly.

**Comment by xpepermint** [comment]
For the sake of simplicity, all the hashes have been calculated by hand and placed in the tests. Replacing hashes with mechanics for calculating objects would be super complex and we would have to actually recreate the Cert class. 
I agree that it could be unclear but maybe we can just add some comments for readability.
