### ISSUE TITLE
Cert/merkle fuzz testing

### ISSUE THREAD

**Issue by fulldecent** [0xcert/framework#336]
The `MerkleValue` interface allows values of *any* type. However the tests only include string values. This test is very limiting and may fail to show errors with other types of inputs.

Please also include tests which expose values that are:

- Array types like the `exampleData` -> `tags` data
- `true`, `false`, `null`
- An empty array
- An empty object
- Integers
- A bunch of weird JSON numbers
  - -0
  - 0
  - Overflows: 9999999999999999999999999
  - Exponents with e+ and E+

**Comment by xpepermint** [comment]
This values will always work because all values are converted to `string`.

```ts
const hasher = (v: any) => sha(256, toString(v)),
```

**Comment by xpepermint** [comment]
Additional tests added here: https://github.com/0xcert/framework/pull/344
