### ISSUE TITLE
ERC-20 transfer documentation

### ISSUE THREAD

**Issue by fulldecent** [0xcert/framework#337]
The `transfer` function documentation reads:

> Transfers _value amount of tokens to address _to, and MUST fire the Transfer event. The function SHOULD throw if the _from account balance does not have enough tokens to spend.

This is insufficiently specific. Also, _from is not defined in this context. Better to say:

> Transfers _value amount of tokens to address _to, and fires the Transfer event. This function throws if the message sender account balance does not have enough tokens to spend.

Also reported upstream: https://github.com/ethereum/EIPs/pull/1744

**Comment by MoMannn** [comment]
#346
