### ISSUE TITLE
ERC-20 nonstandard approve implementation

### ISSUE THREAD

**Issue by fulldecent** [0xcert/framework#338]
The ERC-20 standard states this regarding approve:

> NOTE: To prevent attack vectors like the one described here and discussed here, clients SHOULD make sure to create user interfaces in such a way that they set the allowance first to 0 before setting it to another value for the same spender.

However it also prescribes:

> THOUGH The contract itself shouldn’t enforce it, to allow backwards compatibility with contracts deployed before

In the ERC-20 implementation here, that feature is implemented in the contract which violates the "shouldn't" prescription of the ERC-20 standard.

Now... ERC-20 isn't written in the most formal language, and it doesn't even reference RFC 2119. But I will take liberty and say that the implementation here does not follow the standard.

It is OKAY to not follow standards! But we should document this departure in the function description and also in the class description. Or, we should reconsider this departure. (For reference, OZ follows the standard on this point).

**Comment by MoMannn** [comment]
We decided to follow the standard and handle this in the framework. 
#345
