### ISSUE TITLE
ERC-20 Nonstandard mock implementation

### ISSUE THREAD

**Issue by fulldecent** [0xcert/framework#339]
The ERC-20 standard states: 

> A token contract which creates new tokens SHOULD trigger a Transfer event with the _from address set to 0x0 when tokens are created.

However the `TokenMock` implementation does not follow this rule.

A lawyer might argue that this is currently a legal implementation. But this requires you to assume ERC-20 is using RFC 2119 language, and it doesn't.

Solution: update the implementation or document the departure from standards.

**Comment by MoMannn** [comment]
#340
