### ISSUE TITLE
Specify schemas we support

### ISSUE THREAD

**Issue by fulldecent** [0xcert/framework#378]
> This specification is provided in a machine-readable format using the JSON Schema format also using JSON-LD to connect the digital asset to an optional evidence file.

- [ ] Need to specify the subset of JSON Schema that we support.

# Add-on work

- [ ] Create schema schema to codify what schemas we support

**Comment by xpepermint** [comment]
Here's what we decided. We will create a JSON Schema to validate features of 0xcert schemas. We could add some sort of a playground for this to http://conventions.0xcert.org.

So, added in the pipeline for v2.

**Comment by xpepermint** [comment]
@fulldecent we just have to add TypeScript definitions to `@0xcert/conventions` package - this will be much faster :).

**Comment by fulldecent** [comment]
Having TypeScript definitions is okay. That means the only supported ways to make the JSON files will be using 0xcert Framework. It will not be interoperable. Interoperability can be a feature for later, like v1.1 since it is not a breaking change.

**Comment by xpepermint** [comment]
Well ... interoperability has nothing to do with the implementation. The protocol is interoperable (the same as erc721). 0xcert Framework is Javascript/Typescript implementation thus having Typescript here is valid.

**Comment by fulldecent** [comment]
The protocol is interoperable at the JavaScript/Typescript layer. It is not interoperable at the data model/JSON layer.

**Comment by xpepermint** [comment]
https://github.com/0xcert/framework/pull/595
