### ISSUE TITLE
xcert schema ID vulnerable to birthday attack

### ISSUE THREAD

**Issue by fulldecent** [0xcert/framework#394]
The documentation for ixcert schemaId is:

> Returns a bytes4 of keccak256 of json schema representing 0xcert Protocol convention

As specified, this only provides 32bits of entropy. The cost of a birthday attack collision is only sqrt(2^32) = 2^16. The security of Merkle proofs depends on the correct schema being specified. So if we can get two schemas to collide then the system is broken.

Recommendation: return the full 32-byte hash.

**Comment by MoMannn** [comment]
#419 It actually already is a `bytes32` but I forgot to update the description.
