### ISSUE TITLE
xcert revoke documentation is unclear

### ISSUE THREAD

**Issue by fulldecent** [0xcert/framework#395]
Revoke is documented at:

https://docs.0xcert.org/api/ethereum.html#asset-ledger

> An asynchronous class instance function which destroys a specific assetId of an account. The asset is removed from the account but stays logged in the blockchain. The function is ment to be used by ledger owners to destroy assets of other accounts.

XcertRevokable.revoke

> Revokes a specified Xcert. Reverts if not called from contract owner or authorized 
   * address.

---

Currently the expected outcome of this function is not clear. (Because it is "logged in the blockchain") Here are some possible interpretations:

* The asset is still owned by the current owner, but it is put into a "revoked" status
* The asset is transferred away from the current owner and given to a "purgatory" account, and information about it can still be queried
* The asset is removed from the current owner and it is obliterated, all queries about it will be invalid (i.e. ERC-721 token burned)

**Comment by MoMannn** [comment]
#418 Is this clear enough?
