### ISSUE TITLE
XcertMock documentation error

### ISSUE THREAD

**Issue by fulldecent** [0xcert/framework#398]
The parameter documentation for `bytes4[] memory _capabilities` is missing.

Also, this parameter should probably be `byte[] memory _capabilities`. Or better, it should just be `bytes32 memory _capabilities`.

**Comment by MoMannn** [comment]
For what reason should the parameter type change? It is assumed that capabilities are linked with supported interfaces (extensions to xcert) which are represented with bytes4.  

#414

**Comment by fulldecent** [comment]
Sorry, please ignore this issue. I had confused capabilities with permissions.
