### ISSUE TITLE
utils/Abilitable, what is zeroAbility?

### ISSUE THREAD

**Issue by fulldecent** [0xcert/framework#400]
The name `zeroAbilityCount` is confusing.

Perhaps ``superUserCount``.

**Comment by MoMannn** [comment]
@fulldecent @xpepermint 

#424 

I changed the contract logic, I need feedback before I implement the changes into the framework. 

I remove the zeroAbilityCount so now you can remove the "super admin". I named the main ability **super ability**. 

You can revoke super ability from yourself but an extra check has been added for that to `revokeAbilities` methods. An additional parameter is now needed: `_allowSuperRevoke` and only if this parameter is `true` you can revoke super ability from yourself. This is to prevent accidentally removing your own super ability.

**Comment by MoMannn** [comment]
Contract logic is approved, framework level implementation still needs some discussion. Will finish this next week.

**Comment by xpepermint** [comment]
Ref: https://github.com/0xcert/framework/pull/424
Can we close this @MoMannn ?

**Comment by MoMannn** [comment]
Closing.
