### ISSUE TITLE
xcert/destroy implementation violates the Checks-Effects-Interactions Pattern

### ISSUE THREAD

**Issue by fulldecent** [0xcert/framework#402]
```solidity
...
    super._destroy(_tokenId);
    require(
      tokenOwner == msg.sender || ownerToOperators[tokenOwner][msg.sender],
      NOT_OWNER_OR_OPERATOR
    );
...
```

The check should proceed the destroy function.

**Comment by MoMannn** [comment]
There are no external calls so this should be ok and does not violate checks-effects-interaction pattern. 

The main reason why `require` is after `super.destroy` is for returning failure reason. If a token got destroyed and you wanted to destroy it again you would get `NOT_VALID_NFT` error if we change the order you will get a `NOT_OWNER_OR_OPERATOR` error which is not wrong but it is less specific. 

If there is a case where this code order could still cause potential problems please comment it and I will fix the code order. Less specific error is still better then an potential attack.

**Comment by fulldecent** [comment]
Fair enough, thanks for explaining. Closing issue.
