### ISSUE TITLE
xcert/_transferFrom wastes gas

### ISSUE THREAD

**Issue by fulldecent** [0xcert/framework#403]
The implementation can be optimized using logical deduction. This will save 200 gas on every transfer.

```solidity
    if (supportedInterfaces[0xbedb86fb])
    {
      require(!isPaused, TRANSFERS_DISABLED);
    }
```

* `!supportedInterfaces[0xbedb86fb]` ⇒ `!isPaused`
* `isPaused` ⇒ `supportedInterfaces[0xbedb86fb]`
* ∴ (`supportedInterfaces[0xbedb86fb]` ∧ `isPaused`) ⇔ `isPaused`

This is an optimization, so it should be documented why we do not need to check the supportedInterface.

**Comment by MoMannn** [comment]
#425 
@fulldecent Great find. Totally overlooked this.
