### ISSUE TITLE
iproxy types might be too restrictive

### ISSUE THREAD

**Issue by fulldecent** [0xcert/framework#404]
The current iproxy is:

```
  function execute(
    address _target,
    address _a,               <--- param a
    address _b,               <--- param b
    uint256 _c                 <--- param c
  )
```

And two of the three inputs are only 160-bits wide. Solidity may truncate these to 160-bits.

But here is a function that you might want to create through a proxy which uses MORE than 160 bits, it uses the full 256 bits.

```
  function create(
    address _xcert,
    address _to,
    uint256 _id,
    bytes32 _imprint
  )
```

As current, the minting function might fail to work with ids higher than 2^160.

**Comment by MoMannn** [comment]
Create proxy for this reason does not implement the iproxy interface. You could argue that that this is inconsistent but the only other way I see to solve this is to make the interface of all bytes32 and handle changing types in framework and contracts but this seams like a lot of overhead for generalisation. At the time being I did not seem it worthy but this may change in the future when we add more or more functionalities. Maybe for v2 and leave as it is now? 

@xpepermint @fulldecent

**Comment by xpepermint** [comment]
I'm good with v2.

**Comment by fulldecent** [comment]
Is there any situation where somebody using solidity might use `iproxy` interface? If yes, then we should test that it still works when the created tokenid is very high. That is the only issue.

I don't want this to work when tokenid is low and then suddenly it breaks if tokenid is high.

**Comment by MoMannn** [comment]
Ok I will add additional test with high token ids.
