### ISSUE TITLE
order-gateway inefficient ordering of enums

### ISSUE THREAD

**Issue by fulldecent** [0xcert/framework#408]
It is cheaper to send a `0` than a `1` in a transaction. So the most common enum value should be used first (which is encoded as `0`).

**Comment by fulldecent** [comment]
Specifically

```
  enum ActionKind
  {
    create,
    transfer
  }
```

**Comment by MoMannn** [comment]
@xpepermint @fulldecent Well this is quite up for debate which will actually get used more... I believe create will get used more since I see great application to delegating minting cost. So this is up for discussion I guess?

**Comment by fulldecent** [comment]
Excellent counterpoint. That justification is more than enough to merit closing this issue.
