### ISSUE TITLE
order-gateway claim can be cancelled twice

### ISSUE THREAD

**Issue by fulldecent** [0xcert/framework#409]
Why you let cancel twice?

**Comment by MoMannn** [comment]
So it uses less gas. There is nothing wrong that can happen if someone runs cancel twice and it should be handled in the frontend. Do you see any case why this would cause problems?

**Comment by xpepermint** [comment]
We could add error on estimate gas for this case.

**Comment by fulldecent** [comment]
It is okay that cancel is allowed twice. Perhaps just add a note in the `@notice` documentation since this might be surprising to somebody.

**Comment by MoMannn** [comment]
#438
