### ISSUE TITLE
order-gateway perform violates checks-effects pattern

### ISSUE THREAD

**Issue by fulldecent** [0xcert/framework#410]
```
    orderPerformed[claim] = true;

    _doActions(_data);
```

**Comment by xpepermint** [comment]
@fulldecent Please explain.

**Comment by MoMannn** [comment]
@fulldecent orderPerformed is first set to true so that if anything in _doActions would try to do a reentry attack it would fail since order is already performed. That is the logic behind that or did I miss something?

**Comment by fulldecent** [comment]
In general the Solidity documentation recommends to perform these two tasks in the other order.

There is currently zero risk of a reentrancy attack. However, this code should be updated because 

1. Solidity says so
2. Subclassing or editing this code later could introduce a reentrancy attack. (For example, if _doActions() was extended in a subclass).

**Comment by fulldecent** [comment]
Thank you for the discussion. You are correct, setting completed = true is part of "checking" in the checks-effects pattern.
