### ISSUE TITLE
0xcert Framework Users 👨‍💻

### ISSUE THREAD

**Issue by typwrtr** [0xcert/framework#442]
**We invite all users of the 0xcert Framework to provide any feedback, suggestions, testimonials, or critiques. ✍**

It's essential for us to hear your feedback, and every input will help us improve the Framework. We're looking forward to your comments and support.

Please provide the following information:

```
- Company/Organization
- Project/Dapp with link
- Your Comment/Feedback
```

Please include screenshots of your code or final product. 

If you have suggestions for the [Framework Documentation](https://docs.0xcert.org), we'll be happy to hear from you in [Issue #444](https://github.com/0xcert/framework/issues/444).

---

**我们欢迎0xcert Framework框架的所有用户在此处提供任何反馈，建议或点评。✍**

您的意见将有助于我们改进框架。我们期待您的评论和支持。

请提供一下信息：

```
  - 公司/组织
  - 项目/去中心化应用与链接
  - 点评/反馈
```

请在评论中包含您的源码或0xcert Framework去中心化应用的屏幕截图。

如果您对[0xcert Framework Documentation](https://docs.0xcert.org)有任何建议，我们期待您的反馈于[Issue #444](https://github.com/0xcert/framework/issues/444)。

**Comment by rbcp18** [comment]
- Fabrx CORP (https://www.fabrx.io)
- NFT Creation & Issuance, Point and Click
- https://app.fabrx.io/ (url likely to change in the future)
<img width="1169" alt="screen shot 2019-03-08 at 8 20 49 am" src="https://user-images.githubusercontent.com/45776981/54040872-3788b600-417b-11e9-8113-360c738c2e69.png">

**Comment by davision** [comment]
- [0xcert](https://0xcert.org)
- SwapMarket (https://swpmarket.com)
- Building a decentralized exchange with 0xcert framework helped us really test all the capabilities of the framework and most importantly, saved us a lot of time we would rather need without it.

**Comment by azizazlan** [comment]
Hi All,

I am a developer at thuleen.io -a start-up. We attempt to provide academic certification solution to local Malaysian academic institutions.

Anyway, I want to have a npm script using 0xcert to deploy an AssetLedger and consequently an Asset. Below is my attempt:

```
const {
  AssetLedger,
  AssetLedgerCapability
} = require("@0xcert/ethereum-asset-ledger");
const MetamaskProvider = require("@0xcert/ethereum-metamask-provider");

async function deployNewLedger() {
  let deployedLedger = {};

  const recipe = {
    name: "Some University Academic Certificate",
    symbol: "SUAC",
    uriBase: "www.example.com/tokenMetadata/",
    schemaId:
      "0xa4cf0407b223849773430feaf0949827373c40feb3258d82dd605ed41c5e9a2c", // This is the ID from schema88 available at the top of the github https://github.com/0xcert/framework/blob/master/conventions/88-crypto-collectible-schema.md
    capabilities: [
      AssetLedgerCapability.DESTROY_ASSET,
      AssetLedgerCapability.UPDATE_ASSET,
      AssetLedgerCapability.TOGGLE_TRANSFERS,
      AssetLedgerCapability.REVOKE_ASSET
    ]
  };

  try {
    const provider = new MetamaskProvider();

    deployedLedger = await AssetLedger.deploy(provider, recipe).then(
      mutation => {
        console.log("Deploying new asset ledger, it may take a few minutes.");
        return mutation.complete();
      }
    );
    console.log("Ledger", deployedLedger);
  } catch (e) {
    console.log("Error", e);
    return;
  }
  if (deployedLedger.isCompleted()) {
    console.log("Ledger address", deployedLedger.receiverId);
  }
}
```
But I got error **MetamaskProvider is not a constructor**.

I also tried to use truffle-hd-wallet-provide:

```
const HDWalletProvider = require("truffle-hdwallet-provider");
async function deployNewLedger() {
  let deployedLedger = {};

  const recipe = {
    name: "Some University Academic Certificate",
    symbol: "SUAC",
    uriBase: "www.example.com/tokenMetadata/", 
    schemaId:
      "0xa4cf0407b223849773430feaf0949827373c40feb3258d82dd605ed41c5e9a2c", // This is the ID from schema88 available at the top of the github https://github.com/0xcert/framework/blob/master/conventions/88-crypto-collectible-schema.md
    capabilities: [
      AssetLedgerCapability.DESTROY_ASSET,
      AssetLedgerCapability.UPDATE_ASSET,
      AssetLedgerCapability.TOGGLE_TRANSFERS,
      AssetLedgerCapability.REVOKE_ASSET
    ]
  };

  try {
    const provider = new HDWalletProvider(
      process.env.REACT_APP_MNENONIC,
      `https://rinkeby.infura.io/v3/${process.env.REACT_APP_INFURA_API_KEY}`,
      0
    );
    deployedLedger = await AssetLedger.deploy(provider, recipe).then(
      mutation => {
        console.log("Deploying new asset ledger, it may take a few minutes.");
        return mutation.complete();
      }
    );
    console.log("Ledger", deployedLedger);
  } catch (e) {
    console.log("Error", e);
    return;
  }
  if (deployedLedger.isCompleted()) {
    console.log("Ledger address", deployedLedger.receiverId);
  }
}
```
and this give the **Only absolute URLs are supported** error.

**Comment by MoMannn** [comment]
@azizazlan I answered this question on our gitter: https://gitter.im/0xcert/framework So check it out there :)

**Comment by gnarco** [comment]
HI

I'm CTO & Co-Founder of Arianee (https://arianee.org).
A protocol using NFT to let company (luxury brands mostly) to issue digital certificate to replace paper one.

We use the certification feature of 0xcert to guarantee that a certificate (json file) is unchanged.

We are going live in few days.

Alex

**Comment by fulldecent** [comment]
In general issues want to be closed. Can a success criteria please be identified for this issue?

We do want to invite continued feedback for the 0xcert project. The place to encourage that should be in the README, the project home page and other places.
