### ISSUE TITLE
Documentation Improvements Suggestions ✍

### ISSUE THREAD

**Issue by typwrtr** [0xcert/framework#444]
**Let us know!**

We're looking forward to hearing your opinion and suggestions regarding the [0xcert Framework Documentation](https://docs.0xcert.org).

We'll review your comments and make sure we update it accordingly.

**You may suggest:** ✍

- What part(s) are difficult to understand or lack explanation?
- What part(s) are lacking examples?
- What part(s) would you structure differently and how?
- What part(s) should improve the language or are there any typos?
- Is there anything you'd like to add to it?
- Anything else you'd like to suggest?

Thanks a lot for your inputs and feedback!

If you have suggestions for the [Framework](https://github.com/0xcert/framework) itself, we'll be happy to hear from you [in Issue #442](https://github.com/0xcert/framework/issues/442).

---

**让我们知道！**

我们很希望收取您对[0xcert Framework Documentation](https://docs.0xcert.org)的反馈意见。

我们将审查您的评论，并确保对文档进行相应更新。

**请通知我们** ✍

-   哪些部分难以理解或缺乏解释？
-   哪些部分缺乏例子？
-   哪些部分可以完善结构？如何？
-   哪些部分可以完善语言风格？有任何拼写错误？
-   您有什么想加的内容吗？
-   您想提出其他建议吗？

我们非常感谢您的意见反馈！

如果您对[0xcert Framework](https://github.com/0xcert/framework)框架有任何建议，我们期待您的反馈于[Issue #442](https://github.com/0xcert/framework/issues/442)。

**Comment by Valentine-Mario** [comment]
I suggest the inclusion of Common JS in the documentation so as to reach out to more users out there. Since studies have shown that there are more JS developers than Typescript developers out there.

**Comment by MoMannn** [comment]
@Valentine-Mario Great suggestion. We are working on writing additional tutorials which will be linked from the documentation and some of them will be completely vanilla JS. That should help anyone working in vanilla JS.
