### ISSUE TITLE
Is it Xcert or xcert?

### ISSUE THREAD

**Issue by fulldecent** [0xcert/framework#448]
Here is one sentence where both word stylizations are used interchangeably.

```
   * @dev Destroys a specified Xcert. Reverts if not called from xcert owner or operator.
```

We should have a preferred stylization for this word and use it consistently.

---

# Follow on work

- [x] Also address this in https://github.com/0xcert/docs

**Comment by MoMannn** [comment]
It is `Xcert`. We will go trough the docs and update it all. 

@typwrtr Please double check this in documentation.
I will go trough code comments/descriptions and fix it all.

**Comment by MoMannn** [comment]
#450
