### ISSUE TITLE
Tighten TypeScript style guide

### ISSUE THREAD

**Issue by fulldecent** [0xcert/framework#449]
Currently both

https://github.com/0xcert/framework/blob/master/packages/0xcert-webpack/src/0xcert-ethereum.js

```ts
Object.assign(
  window.$0xcert,
  require('@0xcert/cert'),
  require('@0xcert/ethereum-asset-ledger'),
  require('@0xcert/ethereum-order-gateway'),
  require('@0xcert/ethereum-value-ledger'),
);
```

and 

https://github.com/0xcert/framework/blob/master/packages/0xcert-webpack/src/0xcert-ethereum-value-ledger.js

```ts
Object.assign(
  window.$0xcert,
  require('@0xcert/ethereum-value-ledger')
);
```

are in the code base.

But a more prescriptive TypeScript style guide could reduce this inconsistency in style.

**Comment by xpepermint** [comment]
@fulldecent this only applies to the `0xcert-webpack` module which is a private module (never published) for creating dist files. We don't use typescript there because we use only `require` statements. However, I will add the missing `,` at the end.  Thanks.

**Comment by xpepermint** [comment]
https://github.com/0xcert/framework/pull/452
