### ISSUE TITLE
OrderProxy: Not necessary to sign ActionKind kind

### ISSUE THREAD

**Issue by fulldecent** [0xcert/framework#479]
Just a feature / optimization.

In the order claim there is the field:

```
    ActionKind kind;
```

Instead save in the gateway a mapping from proxy -> kind. Then it is not necessary to pass this in each time. With packing this can be stored in the same word as the proxy address.

**Comment by MoMannn** [comment]
This is needed for dynamic proxy adding. There can be multiple proxies that confide in the same logic that fits a specific ActionKind. This means we do not need to redeploy OrderGateway smart contract but just add the proxy and use an existing ActionKind.

**Comment by xpepermint** [comment]
@fulldecent, comments?

**Comment by fulldecent** [comment]
Agreed, multiple proxies can be the same ActionKind. Example: `transfer` and `safeTransfer`.

But can one proxy be multiple ActionKinds? Like `transfer` is a mint action and a transfer action?

If not (every proxy has only one action type) then that action type can be saved at the time the proxy is added. Luckily the proxy and the action type fit together into one word.

This means it is unnecessary for the action type to be specified as part of the signed data. Instead, the action type may be implied (I.e. looked up) at the same time the proxy is looked up.

**Comment by xpepermint** [comment]
https://github.com/0xcert/framework/pull/566
