### ISSUE TITLE
Imprint fail for complex schema ?

### ISSUE THREAD

**Issue by gnarco** [0xcert/framework#497]
Hi,

It's me again about JSON schema.

Thanks for fixing the last submitted issue !

So I tried to use my final schema, but it seems to fail :(

So here, a simple version of my final schema.

The main chain is "externalContents" which is an array of object.
Clearly, in the exemple, it's an array of object with just a single entry, so it could be a simple array. But of course, it will be a bigger object. I simplified for the example, and try to find the breaking change.

Perhaps, I'm doing something wrong with my schema, or perhaps Xcert doesn't handle complex schema ? 

Thanks !
  
          const schema2 = {
            "$schema":"https://arianeeschema",
            "description": "Arianee Certificate",
            "title":"Arianee Certificate",
            "type": 'object',
            "properties": {
              "name": {
                "type": "string",
                "title": "Name",
                "format": "string",
                "default": ""
              },
               
              
              "externalContents": {
                "required":false,
                "type": "array",
                "title": "External Contents",
                "items": {
                  "type": "object",
                  "title": "External Contents",
                  "properties": {
                    "title": {
                      "type": "string",
                      "title": "Title",
                      "widget": {
                        "id": "string"
                      }
                    },
                  },
             
                },
                                 
              },    
            }
        }; 

        
        const cert2 = new Cert({ schema: schema2 });

        const data2 = {

            "name": "Magic Sword"
          };

        var certif2 =  await cert2.imprint(data2);  
        console.log('Ximprint',certif2);

        const proofs2 = await cert2.notarize(data2);
        console.log('Xproofs',proofs2)

        // calculate imprint
        const imprint2_test = await cert2.calculate(data2, proofs2);
        console.log('Ximprint2',imprint2_test);

**Comment by xpepermint** [comment]
Hum ... we'll check this ...

**Comment by xpepermint** [comment]
Ah ... do you see it https://github.com/0xcert/framework/blob/0bd9977a28d7e063ec8bffe63cbe72a79a50d868/packages/0xcert-cert/src/core/cert.ts#L263. Undefined should be `string`. Sorry for that ... fix coming up ...

**Comment by xpepermint** [comment]
Fixed in `1.5.1`. Ref https://github.com/0xcert/framework/pull/498
