### ISSUE TITLE
Strange behavior with cert.imprint

### ISSUE THREAD

**Issue by gnarco** [0xcert/framework#506]
Hi guys,

I use 0xcert/cert between a web app creating certificates and publishing imprint on the blockchain
and an ionic web app for android / ios to read theses certificates.

On iOS, everything works well, but on android, cert.imprint is "catch", and I got this error :
            {"__zone_symbol__currentTask":{"type":"microTask","state":"notScheduled","source":"Promise.then","zone":"<root>","cancelFn":null,"runCount":0}}

My code 
```
            const cert = new Cert({
                schema : schema
            });

             cert.imprint(data).then((certif) => {
                console.log('certif imprint', certif);

                resolve("0x" + certif);
            }).catch((err) => {
                reject(err)
            });  
```

It's inside a promise

I wanted to give you a small app to reproduce, unfortunately, when I test this small app, it works of course ...

Clearly, because I succeed with another app, it's not a pure "0xcert" bug, but perhaps, you already encountered this kind of bug, and have an idea ...

Thanks !!

**Comment by xpepermint** [comment]
Hum ... I've tested this only in the latest browsers. The error does not look related to cert module. Do other promises work normally? Can you test the browser's crypto module alone (try running sha256) and write the results?

**Comment by gnarco** [comment]
Ok

I found some info, and a workaround.

So there was few things :
- Seems 
            const hashBuffer = yield window['crypto'].subtle.digest(`SHA-${bits}`, msgBuffer);
doesn't work on android browser loaded with ionic in case of using livereload (and pointing to my computer temp URL that is not SSLed). So need to be SSL or on pure local
- Also, got some issue to get my schema, but it's completely out of scope.

So now, it works perfectly !

Thanks

**Comment by xpepermint** [comment]
Good! Browser compatibility is always an issue with Javascript. However, you can add polyfills to overcome this.
