### ISSUE TITLE
How to access AssetLedger.deploy in vuejs?

### ISSUE THREAD

**Issue by efundcity** [0xcert/framework#508]
deploy() {
      const client = this.$0xcert
      const provider = this.$0xcert.provider
      const AssetLedger = this.$0xcert.modules[1]
      const capabilities = [3, 1]
      console.log(this.$0xcert)
      console.log(AssetLedger)
      const mutation = AssetLedger.deploy(provider, {
        name: 'fundin',
        symbol: 'fundin',
        uriBase: 'http://www.fundin.us',
        schemaId:
          '3f4a0870cd6039e6c987b067b0d28de54efea17449175d7a8cd6ec10ab23cc5d',
        capabilities
      }) // You can catch errors by adding .catch((e) => console.log(e)).
      console.log(mutation.id)
    }

I got this error:   AssetLedger.deploy is not a function
How to access AssetLedger.deploy in vuejs?
Thanks

**Comment by xpepermint** [comment]
VueJS and NuxtJS expect a preconfigured global plugin instance which we can use in any component. The 0xcert injects `this.$0xcert` which is basically an instance of the [0xcert VueJS Client](https://github.com/0xcert/framework/blob/master/packages/0xcert-vue-plugin/src/core/client.ts).

```ts
this.$0xcert.deployAssetLedger({ ... })
```

**Comment by efundcity** [comment]
Hello @xpepermint 
Thanks for your help.
i got this error "module.deploy is not a function" when i call this.$0xcert.deployAssetLedger({})

    deploy() {
      const client = this.$0xcert
      const provider = this.$0xcert.provider
      const capabilities = [3, 1]
      console.log(this.$0xcert.deployAssetLedger)
      const mutation = this.$0xcert.deployAssetLedger(provider, {
        name: 'fundin',
        symbol: 'fundin',
        uriBase: 'http://www.fundin.us',
        schemaId:
          '3f4a0870cd6039e6c987b067b0d28de54efea17449175d7a8cd6ec10ab23cc5d',
        capabilities
      }) // You can catch errors by adding .catch((e) => console.log(e)).
      console.log(mutation.id)
    }
Am I miss any things?

**Comment by xpepermint** [comment]
Make sure you pass `deployAssetLedger` only configuration info (no provider).

**Comment by efundcity** [comment]
deploy() {
      const client = this.$0xcert
      const provider = this.$0xcert.provider
      const capabilities = [3, 1]
      //console.log(this.$0xcert.deployAssetLedger)
      const mutation = async function() {
        await client
          .deployAssetLedger({
            name: 'fundin',
            symbol: 'din',
            uriBase: 'http://www.fundin.us',
            schemaId:
              '0x3f4a0870cd6039e6c987b067b0d28de54efea17449175d7a8cd6ec10ab23cc5d',
            capabilities
          })
          .then(mutation => {
            return mutation.complete()
          })
          .catch(e => console.log(e)) // You can catch errors by adding .catch((e) => console.log(e)).
      }
      const assetLedgerId = mutation.receiverId
      console.log(assetLedgerId)
    }
This is new code. 
Didn't get error. 
But the assetLedgerId is undefined. 
if deploy success, it should be show a new record  in metamask history ?

I'm in ropsten test network

**Comment by xpepermint** [comment]
So yeah ... the correct code that works from [here](https://github.com/0xcert/framework/blob/28bb4dd981a08551e4f67d3c6886211145b0580e/packages/0xcert-vue-example/pages/index.vue#L98) is:

```js
const mutation = await this.$0xcert.deployAssetLedger({
  name: 'fundin',
  symbol: 'fundin',
  uriBase: 'http://www.fundin.us',
  schemaId: '0x3f4a0870cd6039e6c987b067b0d28de54efea17449175d7a8cd6ec10ab23cc5d',
  capabilities: [3, 1]
}).then((mutation) => {
  return mutation.complete();
});
console.log('Contract deployed:', {
  tx: mutation.id,
  address: mutation.receiverId,
})
```
Make sure you upgrade your packages to `v1.7.2` which include a small update. This should do the trick.
