### ISSUE TITLE
Can't get TX and address after Contract deployed

### ISSUE THREAD

**Issue by efundcity** [0xcert/framework#511]
console.log can't catch the TX and Address after Contract deployed.
Only show Fetch finished loading: GET "https://conventions.0xcert.org/xcert-mock.json" in console.
Environment:  VUEJS + 0xCert VUE Plugin 1.7.2 + example code + metamask+ropsten test network

    async deployAssetLedger() {
      const mutation = await this.$0xcert
        .deployAssetLedger({
          name: 'fundin',
          symbol: 'fff',
          uriBase: 'http://www.fundin.us',
          schemaId:
            '0x3f4a0870cd6039e6c987b067b0d28de54efea17449175d7a8cd6ec10ab23cc5d',
          capabilities: [3, 1]
        })
        .then(mutation => {
          return mutation.complete()
        })
      console.log('Contract deployed:', {
        tx: mutation.id,
        address: mutation.receiverId
      })
    }

**Comment by xpepermint** [comment]
I tested my example above yesterday and it worked. Note that 

```js
const mutation = await this.$0xcert.deployAssetLedger(...);
```

returns mutation with `mutation.id` set to transaction hash. Executing

```js
await mutation.complete();
```

will wait until the transaction is confirmed X times. This can be configured on the provider through the `requiredConfirmations` option.

The confirmation time depends on the Ethereum network speed and can take up to several minutes. I believe you didn't wait long enough.

**Comment by efundcity** [comment]
I try to run  other example like this:

    async perform() {
      const exchange = await this.$0xcert.getOrderGateway(this.exchangeId)
      const signature = await exchange.claim(this.orderData)
      const mutation = await exchange.perform(this.orderData, signature)
      console.log('Performed order mutation:', mutation)
    }
The console.log still not catch mutation info after 30 mins.

BTW i'm in ropsten test network.

**Comment by xpepermint** [comment]
Well ... it works for me. Are you sure you connected the provider to Ropsten? You have to [enable the provider](https://docs.0xcert.org/guide/using-providers.html#usage-overview) first.

**Comment by efundcity** [comment]
Yes, MetaMask is ready. I check the provider status before deploy.
Here are some screen shot.
Seems the Contract was created by 0x0f220b086ef5Dd45df31D867A36e9d2DF13Ea342 

But I can't catch the TX id and Address.

Usually the contract should be created by my provide.id？

The deploy process looks like holding not completed.  


![erc721-02](https://user-images.githubusercontent.com/50061980/59055639-2c612700-884b-11e9-9e8a-f1695457eb0a.JPG)
![erc721-01](https://user-images.githubusercontent.com/50061980/59055641-2c612700-884b-11e9-894b-a3b6a71a942e.JPG)

Here is the code.

`  methods: {
    async connect() {
      await this.$0xcert.provider.enable()
      const isSupported = this.$0xcert.provider.isSupported()
      const isEnabled = await this.$0xcert.provider.isEnabled()
      console.log('Is metamask supported:', isSupported)
      console.log('Is metamask enabled:', isEnabled)
      if (isSupported && isEnabled) return true
      else return false
    },
    async getData() {
      const state = await this.connect()
      if (!state) {
        console.log('MetaMask Not Ready!!')
      } else {
        const provider = this.$0xcert.provider
        const matches = provider.isCurrentAccount(provider.accountId)
        console.log('accountId:', provider.accountId)
        console.log('isCurrentAccount:', matches)
        this.deploy()
      }
    },
    async deploy() {
      const client = this.$0xcert
      const provider = this.$0xcert.provider
      const capabilities = [3, 1]
      const mutation = await client
        .deployAssetLedger({
          name: 'fundin',
          symbol: 'din',
          uriBase: 'http://www.fundin.us',
          schemaId:
            '0x3f4a0870cd6039e6c987b067b0d28de54efea17449175d7a8cd6ec10ab23cc5d',
          capabilities: capabilities
        })
        .then(async mutation => {
          return await mutation.complete()
          console.log(mutation)
          console.log(client.provider.requiredConfirmations)
        })
      console.log('Contract deployed:', {
        tx: mutation.id,
        address: mutation.receiverId
      })
    }
  }`

**Comment by xpepermint** [comment]
Please push your code to github. Please tell me also which browser you use.

**Comment by efundcity** [comment]
AssetLedger.deploy is not working, Deploy status is in pending all the time;

Environment:
1. chrome 74.0.3729.169
2. metamask 6.6.1
3. windoows 10
4. vuex 3.1.0
5. nuxt 2.0.0
6. ropsten test network

Here is the code.
[https://github.com/efundcity/0xcert_test](url)

**Comment by efundcity** [comment]
I can see the https://conventions.0xcert.org/xcert-mock.json is loaded.

May be is provider.post not working or  something get error.

![deploy-01](https://user-images.githubusercontent.com/50061980/59139352-69124880-8947-11e9-8de0-b0668cc4c862.JPG)

**Comment by efundcity** [comment]
@xpepermint 
I try to trace the code.
seems, the process are stuck here:
`const res = yield this.request(Object.assign({}, payload, { method: 'eth_estimateGas', params: []  }));`
Can not get result, Can not catch any error.

i can get a popup window from metamask. if skip this code.

**Comment by xpepermint** [comment]
Please make sure your repository https://github.com/efundcity/0xcert_test can be used by cloning the repo and running `npm i && npm run dev`.

**Comment by efundcity** [comment]
Solved.
Remove MetaMask & Reinstall it.
Every thing is back to normal.

Thanks for your help.
