### ISSUE TITLE
How to get a specific commit of a package ?

### ISSUE THREAD

**Issue by mvaullerin** [0xcert/framework#520]
Hello,

Following the #519 , I need to update the @0xcert/ethereum-erc721-contracts package on my project before deploying.

I know how to get a specific version (like 1.7.3) but I can't make it work with a specific commit (e.g 6e97e1600aeaa7e7818ddb78a750080ddc61bbc3).

Is there any way to do this ? (I'm using npm)

Thanks.

**Comment by xpepermint** [comment]
This is a monorepo for all the 0xcert packages. It's a long procedure to publish a new version of the framework so you'll have to wait a day or two for this to be released.

**Comment by xpepermint** [comment]
`1.7.4` published, https://github.com/0xcert/framework/pull/521
