### ISSUE TITLE
Document dependencies versions

### ISSUE THREAD

**Issue by fulldecent** [0xcert/framework#53]
This includes code from other projects. The specific allowed versions should be documented in some way.

**Comment by xpepermint** [comment]
Not sure I understand. Dependencies are specified in a `package.json` file of each package.

**Comment by fulldecent** [comment]
Sorry, that wasn't clear.

I meant to say that our release process can be documented and this can include an explanation of how we choose which versions of our dependencies we will use.

For example, it is our polity to bump dependencies on each release? Do we only bump for major versions or when we require a new feature? Will we make release just to bump dependences, or only do this as part of regularly scheduled releases?

I can make a PR for review if interested.

**Comment by xpepermint** [comment]
Agenda for the next call.

**Comment by xpepermint** [comment]
I believe we have this now in the [CONTRIBUTING.md](https://github.com/0xcert/framework/blob/master/CONTRIBUTING.md). I would go with a common and flexible version bump policy. Important changes should always be pushed to `npm`.

**Comment by fulldecent** [comment]
Will it be our policy in general to release a new version every time Solidity makes a release?

**Comment by xpepermint** [comment]
No, but we will try to follow. Best effort mode :).

**Comment by fulldecent** [comment]
Sounds good, thank you for explaining, closing issue.
