### ISSUE TITLE
Upgrade to node 12

### ISSUE THREAD

**Issue by fulldecent** [0xcert/framework#532]
It seems 11 is no longer supported by vendor.

**Comment by xpepermint** [comment]
I tried that many times but some eth-related dependencies are not there yet. Leaving this issue opened until it's possible.

**Comment by fulldecent** [comment]
Cool. I'm seeing the same issue on Nightfall. If/when specific dependencies are identified as problems then an issue can be opened on that dependency's project and a blocker added here.

**Comment by fulldecent** [comment]
There may be good reason to upgrade from Node 11 to Node 10 LTS, for the same reason. And still Node 12 when blockers are fixed.

**Comment by xpepermint** [comment]
If I'm not mistaken, only one package has to be upgraded and it will work. Let's wait some more ...

**Comment by xpepermint** [comment]
Fixed: https://github.com/0xcert/framework/pull/563

When running `rush update --full` still some errors are visible but it works on NodeJS `12.11.0`.

**Comment by fulldecent** [comment]
Awesome! Welcome to the future :-p
