### ISSUE TITLE
Enumeration unnecessary

### ISSUE THREAD

**Issue by fulldecent** [0xcert/framework#54]
The enumeration feature of xcerts is unnecessary.

See for example this implementation: https://github.com/fulldecent/spend-ERC20-create-ERC721 it does not depend on enumeration.

**Comment by fulldecent** [comment]
I added this issue to my agenda for the next phone call. This is one interesting use case we can consider here.

**Comment by MoMannn** [comment]
v1 will go with Enumerable. We shall reconsider this for v2.

**Comment by xpepermint** [comment]
I think this is no longer a question since we added enumerable functions to the AssetLedger. Can we close this? @fulldecent @MoMannn

**Comment by fulldecent** [comment]
Yes, good to close from me
