### ISSUE TITLE
updateAsset error

### ISSUE THREAD

**Issue by qnguyen12** [0xcert/framework#545]
Hi,

I am trying to update asset: https://docs.0xcert.org/api/ethereum.html#updateasset-assetid-recipe
I use your example and add some functions https://github.com/0xcert/framework/tree/master/packages/0xcert-vue-example
Here's the code to create asset:
```
async createAsset() {
        const cert = this.$0xcert.createCert({ schema: this.assetSchema })
        const proofs = await cert.notarize(this.assetData);
        const imprint = await cert.calculate(this.assetData, proofs)
        const asset = {
            id: '0',
            imprint: imprint,
            receiverId: '0x979dd39c046c8E35CB8A94bD0D7B82695e8049b9',
        };
        const ledger = this.$0xcert.getAssetLedger('0x3F48B0027B8C23629347D772963D7cF4A9d73F27')
        const mutation = await ledger.createAsset(asset)
        .then((mutation) => {
            return mutation.complete();
        });
    },
```
I can get successfully
```
async getAsset() {
        const ledger = this.$0xcert.getAssetLedger('0x3F48B0027B8C23629347D772963D7cF4A9d73F27')
        const data = await ledger.getAsset('0')
        console.log(data)
    },
```
but always fail when trying to update asset:

```
async updateAsset() {
        const ledger = this.$0xcert.getAssetLedger('0x3F48B0027B8C23629347D772963D7cF4A9d73F27')
        const cert = this.$0xcert.createCert({ schema: this.assetSchema })
        //update asset name
        this.assetData.name = 'Magic Sword1'
        const proofs = await cert.notarize(this.assetData);
        const imprint = await cert.calculate(this.assetData, proofs)
        const mutation = await ledger.updateAsset('0', {imprint: imprint})
    },
```

The error:

> Error: invalid bytes32 value (arg="", coderType="bytes32", value="44202c5a3052c56aca424fe468712019596eb846aae7d78340fc16044f6d649a")
>     at Object.throwError (vendors.app.js:21614)
>     at CoderFixedBytes.push../node_modules/ethers/utils/abi-coder.js.CoderFixedBytes.encode (vendors.app.js:20436)
>     at vendors.app.js:20608
>     at Array.forEach (<anonymous>)
>     at pack (vendors.app.js:20607)
>     at CoderTuple.push../node_modules/ethers/utils/abi-coder.js.CoderTuple.encode (vendors.app.js:20767)
>     at AbiCoder.push../node_modules/ethers/utils/abi-coder.js.AbiCoder.encode (vendors.app.js:20900)
>     at Encoder.encodeParameters (vendors.app.js:3046)
>     at Object.<anonymous> (vendors.app.js:1150)
>     at Generator.next (<anonymous>)
> value @ vendors.app.js:13758
> value @ vendors.app.js:13758
> value @ vendors.app.js:13758
> (anonymous) @ vendors.app.js:13758
> push../.nuxt/client.js.vue__WEBPACK_IMPORTED_MODULE_18__.default.config.errorHandler @ app.js:411
> globalHandleError @ commons.app.js:11407
> handleError @ commons.app.js:11376
> (anonymous) @ commons.app.js:11393
> Promise.catch (async)
> invokeWithErrorHandling @ commons.app.js:11393
> invoker @ commons.app.js:11716
> original._wrapper @ commons.app.js:16439

I don't know if I use the updateAsset() correctly?

**Comment by MoMannn** [comment]
@qnguyen12 It seems like you found a small bug. 
When imprint is generated its value is without `0x` prefix. `createAsset` automatically adds the `0x` prefix while updateAsset does not. We will fix this with the next versions for now you can make it work by changing this line:
```const mutation = await ledger.updateAsset('0', {imprint: imprint})```
with 
```const mutation = await ledger.updateAsset('0', {imprint: `0x${imprint}`)```

**Comment by xpepermint** [comment]
https://github.com/0xcert/framework/pull/550
