### ISSUE TITLE
101 certification question

### ISSUE THREAD

**Issue by qnguyen12** [0xcert/framework#549]
Hi, noob questions here
In your example at https://docs.0xcert.org/guide/certification.html#usage-overview
You expose description and image publicly at https://troopersgame.com/sword/100.json
But I don't know how the new owner knows all data which includes **name** in case the owner transfers asset?

**Comment by xpepermint** [comment]
Not a noob question :). Full asset document should be stored in a central database or in a local file and should be owned by `holder` and `provider`. After a `provider` issues a new asset for a `holder`, he also sends full asset document to `holder` using an arbitrary communication channel.
