### ISSUE TITLE
uriBase and URI of tokens

### ISSUE THREAD

**Issue by qnguyen12** [0xcert/framework#551]
Hi, another basic questions need your helps.

I know that every asset ledger has a uriBase such as myhost.com/tokens/
and after generating a token, URI of a token is myhost.com/tokens/{tokenId}
However, I don't know what information do we show? Is it a json file or a web page?

Many thanks

**Comment by MoMannn** [comment]
We show a json file describing the NFT(its metadata). Here is a more detailed explanation: https://docs.0xcert.org/guide/certification.html#usage-overview you can see the actual example under: `The metadata URL should respond with the metadata object that looks like the one below:`

**Comment by qnguyen12** [comment]
Thanks
In your example, you show data that are exposed publicly (description, image), $evidence and $schema.
So, do we must define which data is exposed publicly and use `disclose` to have evidence URL?

**Comment by xpepermint** [comment]
Yes, you extract public data from a full data object using [disclose](https://docs.0xcert.org/api/core.html#disclose-data-paths) (for $evidence) and [expose](https://docs.0xcert.org/api/core.html#expose-data-paths) methods (for public metadata json).

**Comment by qnguyen12** [comment]
Thanks,
These are steps to have a uri of tokens, I don't know if it's ok?
1. use disclose to have evidence data, then upload and assign the URL to $evidence.
2. assign schema url to $schema.
3. use expose to get public data (do not have to use if we decide to expose all?)
=> Combine these we will have a public metadata and store at myhost.com/tokens/{tokenId}

**Comment by xpepermint** [comment]
Sounds correct.
