### ISSUE TITLE
Update bitski versions.

### ISSUE THREAD

**Issue by MoMannn** [0xcert/framework#568]
Update bitski versions in bitski related packages.

**Comment by qnguyen12** [comment]
Please support Network too
https://github.com/BitskiCo/bitski-js#getting-a-provider

**Comment by xpepermint** [comment]
@qnguyen12 network should already be supported https://github.com/0xcert/framework/blob/master/packages/0xcert-ethereum-bitski-backend-provider/src/core/provider.ts#L68. Is this something you were looking for?

**Comment by qnguyen12** [comment]
@xpepermint 
I mean the custom chain
`const network = {
  rpcUrl: 'http://localhost:9545',
  chainId: 9,
}
const provider = bitski.getProvider({ network: network });`

**Comment by MoMannn** [comment]
#581

**Comment by xpepermint** [comment]
This has been merged to `2.0` branch. Unfortunately, we won't be adding this feature to `1.0`.
