### ISSUE TITLE
INVALID_ALT_NUMBER when rebuilding

### ISSUE THREAD

**Issue by xpepermint** [0xcert/framework#693]
I see a warning when running `rush rebuild` with the latest dependencies:
 
```
@0xcert/ethereum-utils-contracts (26.12 seconds)
(node:92950) Warning: Accessing non-existent property ‘INVALID_ALT_NUMBER’ of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
(node:92950) Warning: Accessing non-existent property ‘INVALID_ALT_NUMBER’ of module exports inside circular dependency
```

**Comment by MoMannn** [comment]
@xpepermint Which node version are you using?

**Comment by xpepermint** [comment]
`v14.2.0` only.
`v12.18.0` looks ok.

Maybe we just ignore the warning since it's not a problem of this framework but of a dependency?

**Comment by MoMannn** [comment]
Looks like this is a problem with specrons dependency which is used for testing so it should not be a problem in production. We have forwarded the problem.

https://github.com/specron/framework/issues/95
