### ISSUE TITLE
Broken link https://conventions.0xcert.org.

### ISSUE THREAD

**Issue by fulldecent** [0xcert/framework#695]
https://conventions.0xcert.org is a broken link in the 0xcert-conventions package.

**Comment by xpepermint** [comment]
@fulldecent all the links from the documentation should work. We just don't have the "index" at that domain. If you find a link that doesn't work, please post it here and we'll fix it. Thanks

**Comment by xpepermint** [comment]
Fixed: https://github.com/0xcert/framework/pull/698
