### ISSUE TITLE
Remove arithmetic check asserts

### ISSUE THREAD

**Issue by fulldecent** [0xcert/framework#710]
Currently we use like

```
        assert(ownerToNFTokenCount[owner] > 0);
        ownerToNFTokenCount[owner] = ownerToNFTokenCount[owner] - 1;
```

This is no longer necessary with Solidity 0.8.x. And because we are advertising a gas-optimized implementation, we should remove these unnecessary lines. Or can comment them out like:

```
        // assert(ownerToNFTokenCount[owner] > 0); Solidity 0.8
        ownerToNFTokenCount[owner] -= 1;
```

I have also been doing this on other projects:

```
pragma solidity 0.8.0; // code below expects that integer overflows will revert
```

just to be extra careful.

**Comment by xpepermint** [comment]
PRs are merged. Should we close this issue?

**Comment by fulldecent** [comment]
Good to close
